FormulaOneShots/Controllers/GuessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FormulaOneShots.Data;
using FormulaOneShots.Models;

namespace FormulaOneShots.Controllers
{
    public class GuessController : Controller
    {
        private readonly GuessesContext _context;

        public GuessController(GuessesContext context)
        {
            _context = context;
        }

        // GET: Guess
        public async Task<IActionResult> Index()
        {
              return _context.Shots != null ? 
                          View(await _context.Shots.ToListAsync()) :
                          Problem("Entity set 'GuessesContext.Shots'  is null.");
        }

        // GET: Guess/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Shots == null)
            {
                return NotFound();
            }

            var shots = await _context.Shots
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shots == null)
            {
                return NotFound();
            }

            return View(shots);
        }

        // GET: Guess/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guess/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,User,Year,Race,PolePosition,RandomGuess,LastChange")] Shots shots)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shots);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shots);
        }

        // GET: Guess/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Shots == null)
            {
                return NotFound();
            }

            var shots = await _context.Shots.FindAsync(id);
            if (shots == null)
            {
                return NotFound();
            }
            return View(shots);
        }

        // POST: Guess/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,User,Year,Race,PolePosition,RandomGuess,LastChange")] Shots shots)
        {
            if (id != shots.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shots);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShotsExists(shots.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shots);
        }

        // GET: Guess/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Shots == null)
            {
                return NotFound();
            }

            var shots = await _context.Shots
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shots == null)
            {
                return NotFound();
            }

            return View(shots);
        }

        // POST: Guess/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Shots == null)
            {
                return Problem("Entity set 'GuessesContext.Shots'  is null.");
            }
            var shots = await _context.Shots.FindAsync(id);
            if (shots != null)
            {
                _context.Shots.Remove(shots);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShotsExists(int id)
        {
          return (_context.Shots?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FormulaOneShots/Controllers/ShotsController.cs
using Microsoft.AspNetCore.Mvc;

namespace FormulaOneShots.Controllers;

public class ShotsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

FormulaOneShots/Controllers/StandingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace FormulaOneShots.Controllers;

public class StandingsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

FormulaOneShots/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FormulaOneShots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/FormulaOneShots.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FormulaOneShots</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Shots" asp-action="Index">Shots</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Standings" asp-action="Index">Standings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guess" asp-action="Index">Guess</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - FormulaOneShots - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>